from app.routers.AImodel.memory import (
    POSTGRES_AIMODEL_MEMORY_SCHEMA_SQL,
    AiModelMemoryMessage,
    AiModelUserMemory,
    NoopAiModelMemoryStore,
    extract_user_memories_from_text,
)


def test_aimodel_memory_schema_uses_integer_ids_without_physical_foreign_keys() -> None:
    schema_sql = "\n".join(POSTGRES_AIMODEL_MEMORY_SCHEMA_SQL)
    normalized_schema = " ".join(schema_sql.split())

    assert "CREATE TABLE IF NOT EXISTS conversation" in schema_sql
    assert "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in schema_sql
    assert "user_id INTEGER NOT NULL" in schema_sql
    assert "user_id VARCHAR" not in schema_sql
    assert "title VARCHAR(40)" in schema_sql
    assert "conversation_id TEXT" not in schema_sql
    assert "metadata JSONB" not in schema_sql
    assert "CREATE TABLE IF NOT EXISTS message" in schema_sql
    assert "conversation_id INTEGER NOT NULL" in schema_sql
    assert "REFERENCES conversation" not in schema_sql
    assert "CREATE TABLE IF NOT EXISTS user_memory" in schema_sql
    assert "CREATE TABLE IF NOT EXISTS message_query_trace" in schema_sql
    assert "message_id INTEGER NOT NULL" in schema_sql
    assert "query_trace_id TEXT NOT NULL" in schema_sql
    assert "REFERENCES message" not in schema_sql
    assert "REFERENCES rag_query_traces" not in schema_sql
    assert (
        "TRUNCATE TABLE message_query_trace, message, conversation, user_memory"
        in normalized_schema
    )


def test_noop_aimodel_memory_store_generates_conversation_id_and_keeps_recent_messages() -> None:
    store = NoopAiModelMemoryStore()

    conversation_id = store.ensure_conversation(None, user_id=1, first_message="我喜欢小米")
    for index in range(6):
        store.append_user_message(conversation_id, user_id=1, content=f"用户消息 {index}", links=[])

    recent_messages = store.load_recent_messages(conversation_id, limit=5)

    assert conversation_id == 1
    assert [message.content for message in recent_messages] == [
        "用户消息 1",
        "用户消息 2",
        "用户消息 3",
        "用户消息 4",
        "用户消息 5",
    ]


def test_extract_user_memories_from_text_detects_price_and_brand_preferences() -> None:
    memories = extract_user_memories_from_text(
        "我喜欢小米，也比较看重高性价比，预算有限。",
        user_id=1,
    )

    assert AiModelUserMemory(
        memory_type="brand_preference",
        memory_value="小米",
        evidence="用户表达了对小米的品牌偏好。",
        confidence=0.8,
    ) in memories
    assert AiModelUserMemory(
        memory_type="price_preference",
        memory_value="高性价比",
        evidence="用户表达了高性价比或预算敏感偏好。",
        confidence=0.7,
    ) in memories


def test_noop_aimodel_memory_store_upserts_user_memory() -> None:
    store = NoopAiModelMemoryStore()
    store.upsert_user_memory(
        1,
        memory_type="price_preference",
        memory_value="高性价比",
        evidence="用户关注高性价比",
        confidence=0.7,
    )

    assert store.load_user_memories(1) == [
        AiModelUserMemory(
            memory_type="price_preference",
            memory_value="高性价比",
            evidence="用户关注高性价比",
            confidence=0.7,
        )
    ]


def test_memory_message_dataclass_shape() -> None:
    message = AiModelMemoryMessage(role="assistant", content="推荐看高性价比商品。")

    assert message.role == "assistant"
    assert message.content == "推荐看高性价比商品。"


def test_noop_aimodel_memory_store_lists_conversations_and_messages_by_int_user_id() -> None:
    store = NoopAiModelMemoryStore()
    first_id = store.ensure_conversation(None, user_id=1, first_message="第一轮")
    second_id = store.ensure_conversation(None, user_id=1, first_message="第二轮")
    other_user_id = store.ensure_conversation(None, user_id=2, first_message="其他用户")
    store.append_user_message(first_id, user_id=1, content="第一轮", links=["/items/item_a"])
    store.append_assistant_message(
        first_id,
        user_id=1,
        content="第一轮回答",
        recommended_links=[{"item_id": "item_a", "item_name": "商品A", "url": "/items/item_a"}],
    )

    conversations = store.list_conversations(user_id=1)
    messages = store.list_messages(first_id, user_id=1)

    assert [conversation.id for conversation in conversations] == [second_id, first_id]
    assert [conversation.title for conversation in conversations] == ["第二轮", "第一轮"]
    assert store.list_messages(other_user_id, user_id=1) == []
    assert [(message.role, message.content) for message in messages] == [
        ("user", "第一轮"),
        ("assistant", "第一轮回答"),
    ]
    assert messages[0].links == ["/items/item_a"]
    assert messages[1].recommended_links == [{"item_id": "item_a", "item_name": "商品A", "url": "/items/item_a"}]


def test_noop_store_associates_assistant_message_with_multiple_query_traces() -> None:
    """One Agent answer may consume multiple RAG query tool results."""

    store = NoopAiModelMemoryStore()
    conversation_id = store.ensure_conversation(None, user_id=1, first_message="对比商品")

    message_id = store.append_assistant_message(
        conversation_id,
        user_id=1,
        content="对比结论",
        recommended_links=[],
        query_trace_ids=["query-a", "query-b", "query-a"],
    )

    assert message_id == 1
    assert store.list_message_query_traces(message_id) == ["query-a", "query-b"]
