from app.routers.AImodel.memory import (
    POSTGRES_AIMODEL_MEMORY_SCHEMA_SQL,
    AiModelMemoryMessage,
    AiModelUserMemory,
    NoopAiModelMemoryStore,
    extract_user_memories_from_text,
)


def test_aimodel_memory_schema_uses_integer_ids_without_physical_foreign_keys() -> None:
    schema_sql = "\n".join(POSTGRES_AIMODEL_MEMORY_SCHEMA_SQL)

    assert "CREATE TABLE IF NOT EXISTS conversation" in schema_sql
    assert "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in schema_sql
    assert "title VARCHAR(40)" in schema_sql
    assert "conversation_id TEXT" not in schema_sql
    assert "metadata JSONB" not in schema_sql
    assert "CREATE TABLE IF NOT EXISTS message" in schema_sql
    assert "conversation_id INTEGER NOT NULL" in schema_sql
    assert "REFERENCES conversation" not in schema_sql
    assert "CREATE TABLE IF NOT EXISTS user_memory" in schema_sql


def test_noop_aimodel_memory_store_generates_conversation_id_and_keeps_recent_messages() -> None:
    store = NoopAiModelMemoryStore()

    conversation_id = store.ensure_conversation(None, user_id="anon_test", first_message="我喜欢小米")
    for index in range(6):
        store.append_user_message(conversation_id, user_id="anon_test", content=f"用户消息 {index}", links=[])

    recent_messages = store.load_recent_messages(conversation_id, limit=5)

    assert conversation_id == 1
    assert [message.content for message in recent_messages] == [
        "用户消息 1",
        "用户消息 2",
        "用户消息 3",
        "用户消息 4",
        "用户消息 5",
    ]


def test_extract_user_memories_from_text_detects_price_and_brand_preferences() -> None:
    memories = extract_user_memories_from_text(
        "我喜欢小米，也比较看重高性价比，预算有限。",
        user_id="anon_test",
    )

    assert AiModelUserMemory(
        memory_type="brand_preference",
        memory_value="小米",
        evidence="用户表达了对小米的品牌偏好。",
        confidence=0.8,
    ) in memories
    assert AiModelUserMemory(
        memory_type="price_preference",
        memory_value="高性价比",
        evidence="用户表达了高性价比或预算敏感偏好。",
        confidence=0.7,
    ) in memories


def test_noop_aimodel_memory_store_upserts_user_memory() -> None:
    store = NoopAiModelMemoryStore()
    store.upsert_user_memory(
        "anon_test",
        memory_type="price_preference",
        memory_value="高性价比",
        evidence="用户关注高性价比",
        confidence=0.7,
    )

    assert store.load_user_memories("anon_test") == [
        AiModelUserMemory(
            memory_type="price_preference",
            memory_value="高性价比",
            evidence="用户关注高性价比",
            confidence=0.7,
        )
    ]


def test_memory_message_dataclass_shape() -> None:
    message = AiModelMemoryMessage(role="assistant", content="推荐看高性价比商品。")

    assert message.role == "assistant"
    assert message.content == "推荐看高性价比商品。"
