"""Generate stable identities for source-addressable RAG chunks.

This module owns the chunk identity algorithm used by ingestion and storage.
Keeping the algorithm outside ``DocumentChunker`` gives every future ingestion
path one canonical implementation and prevents incompatible IDs from being
generated by scripts, batch jobs, or pipeline adapters.
"""

from __future__ import annotations

import json
from collections.abc import Sequence
from hashlib import sha256


def build_chunk_id(
    *,
    source_path: str,
    section_path: str | Sequence[str] | None,
    text: str,
) -> str:
    """Build a deterministic ID from source, logical section, and content.

    Args:
        source_path: Canonical source identity. Callers should use the resolved
            document path when available and the stable document ID otherwise.
        section_path: Active logical heading path for the chunk. A string is
            treated as one path component; sequences preserve component
            boundaries so ``["a/b"]`` cannot collide with ``["a", "b"]``.
        text: Exact chunk text before semantic transform stages rewrite it.

    Returns:
        A lowercase SHA256 hexadecimal digest. Repeating the same three inputs
        produces the same identifier across processes and ingestion runs.

    Raises:
        ValueError: If ``source_path`` or ``text`` is blank.

    Notes:
        The serialized payload includes explicit field boundaries instead of
        directly concatenating strings. This still implements
        ``hash(source_path + section_path + content_hash)`` while avoiding
        ambiguous combinations that could otherwise produce the same payload.
    """

    if not source_path.strip():
        raise ValueError("source_path must not be blank")
    if not text.strip():
        raise ValueError("text must not be blank")

    normalized_section_path = _normalize_section_path(section_path)
    content_hash = sha256(text.encode("utf-8")).hexdigest()
    payload = json.dumps(
        {
            "source_path": source_path,
            "section_path": normalized_section_path,
            "content_hash": content_hash,
        },
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    )
    return sha256(payload.encode("utf-8")).hexdigest()


def _normalize_section_path(
    section_path: str | Sequence[str] | None,
) -> list[str]:
    """Normalize supported section representations without losing boundaries.

    Args:
        section_path: Optional string or ordered sequence supplied by loader or
            chunk adaptation metadata.

    Returns:
        An ordered list of non-blank path components.
    """

    if section_path is None:
        return []
    if isinstance(section_path, str):
        return [section_path] if section_path else []
    return [str(component) for component in section_path if str(component)]
