import os
import re
import threading
from dataclasses import dataclass
from datetime import datetime
from functools import lru_cache
from typing import Any, Literal, Protocol


POSTGRES_AIMODEL_MEMORY_SCHEMA_SQL = [
    """
    CREATE TABLE IF NOT EXISTS conversation (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        source VARCHAR(20) NOT NULL DEFAULT 'web',
        title VARCHAR(40),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_conversation_user_updated_at
    ON conversation(user_id, updated_at DESC, id DESC)
    """,
    """
    CREATE TABLE IF NOT EXISTS message (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        conversation_id INTEGER NOT NULL,
        user_id INTEGER NOT NULL,
        role VARCHAR(20) NOT NULL CHECK (role IN ('user', 'assistant')),
        content TEXT NOT NULL,
        links JSONB NOT NULL DEFAULT '[]'::jsonb,
        recommended_links JSONB NOT NULL DEFAULT '[]'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_message_conversation_created_at
    ON message(conversation_id, created_at DESC, id DESC)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_message_user_created_at
    ON message(user_id, created_at DESC, id DESC)
    """,
    """
    CREATE TABLE IF NOT EXISTS message_query_trace (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        message_id INTEGER NOT NULL,
        query_trace_id TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (message_id, query_trace_id)
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_message_query_trace_message_id
    ON message_query_trace(message_id, id ASC)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_message_query_trace_trace_id
    ON message_query_trace(query_trace_id)
    """,
    """
    CREATE TABLE IF NOT EXISTS agent_trace (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        agent_trace_id TEXT NOT NULL UNIQUE,
        conversation_id INTEGER,
        message_id INTEGER,
        user_query TEXT NOT NULL,
        intent_route JSONB NOT NULL DEFAULT '{}'::jsonb,
        allowed_tools JSONB NOT NULL DEFAULT '[]'::jsonb,
        query_trace_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
        error TEXT,
        started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        completed_at TIMESTAMPTZ
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agent_trace_conversation
    ON agent_trace(conversation_id, started_at DESC, id DESC)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agent_trace_message
    ON agent_trace(message_id, started_at DESC, id DESC)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agent_trace_query_trace_ids
    ON agent_trace USING GIN(query_trace_ids)
    """,
    """
    CREATE TABLE IF NOT EXISTS agent_trace_event (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        agent_trace_id TEXT NOT NULL,
        event_type VARCHAR(40) NOT NULL,
        tool_name VARCHAR(120),
        status VARCHAR(30) NOT NULL,
        duration_ms NUMERIC(12, 3),
        summary_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
        error TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agent_trace_event_trace_created
    ON agent_trace_event(agent_trace_id, created_at ASC, id ASC)
    """,
    """
    CREATE TABLE IF NOT EXISTS user_memory (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        memory_type VARCHAR(40) NOT NULL,
        memory_value VARCHAR(120) NOT NULL,
        evidence TEXT,
        confidence NUMERIC(4, 3) NOT NULL DEFAULT 0.500,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (user_id, memory_type, memory_value)
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_user_memory_user_type
    ON user_memory(user_id, memory_type, updated_at DESC)
    """,
    """
    DO $$
    DECLARE
        needs_user_id_migration BOOLEAN;
    BEGIN
        SELECT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name IN ('conversation', 'message', 'user_memory')
              AND column_name = 'user_id'
              AND data_type NOT IN ('integer')
        ) INTO needs_user_id_migration;

        IF needs_user_id_migration THEN
            TRUNCATE TABLE message_query_trace, message, conversation, user_memory
            RESTART IDENTITY;
            ALTER TABLE conversation ALTER COLUMN user_id TYPE INTEGER USING NULL::INTEGER;
            ALTER TABLE message ALTER COLUMN user_id TYPE INTEGER USING NULL::INTEGER;
            ALTER TABLE user_memory ALTER COLUMN user_id TYPE INTEGER USING NULL::INTEGER;
        END IF;
    END $$;
    """,
]


@dataclass(frozen=True)
class AiModelMemoryMessage:
    role: Literal["user", "assistant"]
    content: str


@dataclass(frozen=True)
class AiModelUserMemory:
    memory_type: str
    memory_value: str
    evidence: str | None
    confidence: float


@dataclass(frozen=True)
class AiModelConversationSummary:
    id: int
    title: str | None
    created_at: datetime | None = None
    updated_at: datetime | None = None


@dataclass(frozen=True)
class AiModelStoredMessage:
    id: int
    role: Literal["user", "assistant"]
    content: str
    links: list[str]
    recommended_links: list[dict[str, Any]]
    created_at: datetime | None = None


class AiModelMemoryStore(Protocol):
    def initialize(self) -> None: ...

    def ensure_conversation(self, conversation_id: int | None, *, user_id: int, first_message: str) -> int: ...

    def load_recent_messages(self, conversation_id: int, *, limit: int = 5) -> list[AiModelMemoryMessage]: ...

    def load_user_memories(self, user_id: int, *, limit: int = 10) -> list[AiModelUserMemory]: ...

    def append_user_message(self, conversation_id: int, *, user_id: int, content: str, links: list[str]) -> None: ...

    def append_assistant_message(
        self,
        conversation_id: int,
        *,
        user_id: int,
        content: str,
        recommended_links: list[dict[str, str]],
        query_trace_ids: list[str] | None = None,
    ) -> int: ...

    def list_message_query_traces(self, message_id: int) -> list[str]: ...

    def persist_agent_trace(self, trace_record: dict[str, Any]) -> None: ...

    def upsert_user_memory(
        self,
        user_id: int,
        *,
        memory_type: str,
        memory_value: str,
        evidence: str | None,
        confidence: float,
    ) -> None: ...

    def list_conversations(self, *, user_id: int) -> list[AiModelConversationSummary]: ...

    def list_messages(self, conversation_id: int, *, user_id: int) -> list[AiModelStoredMessage]: ...


class NoopAiModelMemoryStore:
    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._next_conversation_id = 1
        self._next_message_id = 1
        self._next_sort_order = 1
        self._conversations: dict[int, tuple[int, str, int]] = {}
        self._messages: dict[int, list[AiModelStoredMessage]] = {}
        self._message_query_traces: dict[int, list[str]] = {}
        self._memories: dict[int, dict[tuple[str, str], AiModelUserMemory]] = {}

    def initialize(self) -> None:
        return None

    def ensure_conversation(self, conversation_id: int | None, *, user_id: int, first_message: str) -> int:
        with self._lock:
            if conversation_id is not None:
                self._conversations.setdefault(
                    conversation_id,
                    (user_id, _build_conversation_title(first_message), self._next_sort_order),
                )
                self._next_sort_order += 1
                self._messages.setdefault(conversation_id, [])
                return conversation_id
            conversation_id = self._next_conversation_id
            self._next_conversation_id += 1
            self._conversations[conversation_id] = (user_id, _build_conversation_title(first_message), self._next_sort_order)
            self._next_sort_order += 1
            self._messages.setdefault(conversation_id, [])
            return conversation_id

    def load_recent_messages(self, conversation_id: int, *, limit: int = 5) -> list[AiModelMemoryMessage]:
        with self._lock:
            return [
                AiModelMemoryMessage(role=message.role, content=message.content)
                for message in self._messages.get(conversation_id, [])[-limit:]
            ]

    def load_user_memories(self, user_id: int, *, limit: int = 10) -> list[AiModelUserMemory]:
        with self._lock:
            memories = list(self._memories.get(user_id, {}).values())
        return sorted(memories, key=lambda memory: memory.confidence, reverse=True)[:limit]

    def append_user_message(self, conversation_id: int, *, user_id: int, content: str, links: list[str]) -> None:
        with self._lock:
            # 中文注释：Noop store 也保留完整消息结构，保证前端会话历史测试不依赖真实数据库。
            self._messages.setdefault(conversation_id, []).append(
                AiModelStoredMessage(
                    id=self._next_message_id,
                    role="user",
                    content=content,
                    links=links,
                    recommended_links=[],
                )
            )
            self._next_message_id += 1

    def append_assistant_message(
        self,
        conversation_id: int,
        *,
        user_id: int,
        content: str,
        recommended_links: list[dict[str, str]],
        query_trace_ids: list[str] | None = None,
    ) -> int:
        with self._lock:
            message_id = self._next_message_id
            self._messages.setdefault(conversation_id, []).append(
                AiModelStoredMessage(
                    id=message_id,
                    role="assistant",
                    content=content,
                    links=[],
                    recommended_links=recommended_links,
                )
            )
            self._next_message_id += 1
            self._message_query_traces[message_id] = _normalize_query_trace_ids(
                query_trace_ids
            )
            return message_id

    def list_message_query_traces(self, message_id: int) -> list[str]:
        """Return query traces consumed by one stored assistant message."""

        with self._lock:
            return list(self._message_query_traces.get(message_id, []))

    def persist_agent_trace(self, trace_record: dict[str, Any]) -> None:
        """Accept Agent Trace records in tests without external storage."""

        return None

    def upsert_user_memory(
        self,
        user_id: int,
        *,
        memory_type: str,
        memory_value: str,
        evidence: str | None,
        confidence: float,
    ) -> None:
        with self._lock:
            self._memories.setdefault(user_id, {})[(memory_type, memory_value)] = AiModelUserMemory(
                memory_type=memory_type,
                memory_value=memory_value,
                evidence=evidence,
                confidence=confidence,
            )

    def list_conversations(self, *, user_id: int) -> list[AiModelConversationSummary]:
        with self._lock:
            conversations = [
                AiModelConversationSummary(id=conversation_id, title=title)
                for conversation_id, (stored_user_id, title, _sort_order) in self._conversations.items()
                if stored_user_id == user_id
            ]
            sort_orders = {
                conversation_id: sort_order
                for conversation_id, (stored_user_id, _title, sort_order) in self._conversations.items()
                if stored_user_id == user_id
            }
        return sorted(conversations, key=lambda conversation: sort_orders[conversation.id], reverse=True)

    def list_messages(self, conversation_id: int, *, user_id: int) -> list[AiModelStoredMessage]:
        with self._lock:
            conversation = self._conversations.get(conversation_id)
            if conversation is None or conversation[0] != user_id:
                return []
            return list(self._messages.get(conversation_id, []))


class PostgresAiModelMemoryStore:
    def __init__(self, database_url: str) -> None:
        self.database_url = database_url.replace("postgresql+psycopg://", "postgresql://")
        self._init_lock = threading.Lock()
        self._initialized = False

    def initialize(self) -> None:
        with self._init_lock:
            if self._initialized:
                return
            with self._connect() as connection:
                with connection.cursor() as cursor:
                    for statement in POSTGRES_AIMODEL_MEMORY_SCHEMA_SQL:
                        cursor.execute(statement)
                connection.commit()
            self._initialized = True

    def ensure_conversation(self, conversation_id: int | None, *, user_id: int, first_message: str) -> int:
        self.initialize()
        title = _build_conversation_title(first_message)
        with self._connect() as connection:
            with connection.cursor() as cursor:
                if conversation_id is None:
                    # 中文注释：首次对话由数据库生成数字会话 ID，前端后续用该 ID 继续窗口会话。
                    cursor.execute(
                        """
                        INSERT INTO conversation (user_id, source, title)
                        VALUES (%s, 'web', %s)
                        RETURNING id
                        """,
                        (user_id, title),
                    )
                    row = cursor.fetchone()
                    conversation_id = int(row[0])
                else:
                    # 中文注释：继续已有会话时只刷新更新时间，不依赖物理外键约束。
                    cursor.execute(
                        """
                        INSERT INTO conversation (id, user_id, source, title)
                        VALUES (%s, %s, 'web', %s)
                        ON CONFLICT (id) DO UPDATE SET
                            user_id = EXCLUDED.user_id,
                            updated_at = now()
                        """,
                        (conversation_id, user_id, title),
                    )
            connection.commit()
        return conversation_id

    def load_recent_messages(self, conversation_id: int, *, limit: int = 5) -> list[AiModelMemoryMessage]:
        self.initialize()
        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT role, content
                    FROM message
                    WHERE conversation_id = %s
                    ORDER BY created_at DESC, id DESC
                    LIMIT %s
                    """,
                    (conversation_id, limit),
                )
                rows = cursor.fetchall()
        return [
            AiModelMemoryMessage(role=row[0], content=row[1])
            for row in reversed(rows)
            if row[0] in {"user", "assistant"}
        ]

    def load_user_memories(self, user_id: int, *, limit: int = 10) -> list[AiModelUserMemory]:
        self.initialize()
        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT memory_type, memory_value, evidence, confidence
                    FROM user_memory
                    WHERE user_id = %s
                    ORDER BY confidence DESC, updated_at DESC, id DESC
                    LIMIT %s
                    """,
                    (user_id, limit),
                )
                rows = cursor.fetchall()
        return [
            AiModelUserMemory(
                memory_type=row[0],
                memory_value=row[1],
                evidence=row[2],
                confidence=float(row[3]),
            )
            for row in rows
        ]

    def append_user_message(self, conversation_id: int, *, user_id: int, content: str, links: list[str]) -> None:
        self.initialize()
        from psycopg.types.json import Jsonb

        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO message (conversation_id, user_id, role, content, links)
                    VALUES (%s, %s, 'user', %s, %s)
                    """,
                    (conversation_id, user_id, content, Jsonb(links)),
                )
                cursor.execute("UPDATE conversation SET updated_at = now() WHERE id = %s", (conversation_id,))
            connection.commit()

    def append_assistant_message(
        self,
        conversation_id: int,
        *,
        user_id: int,
        content: str,
        recommended_links: list[dict[str, str]],
        query_trace_ids: list[str] | None = None,
    ) -> int:
        self.initialize()
        from psycopg.types.json import Jsonb

        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO message (conversation_id, user_id, role, content, recommended_links)
                    VALUES (%s, %s, 'assistant', %s, %s)
                    RETURNING id
                    """,
                    (conversation_id, user_id, content, Jsonb(recommended_links)),
                )
                message_id = int(cursor.fetchone()[0])
                for query_trace_id in _normalize_query_trace_ids(query_trace_ids):
                    cursor.execute(
                        """
                        INSERT INTO message_query_trace (message_id, query_trace_id)
                        VALUES (%s, %s)
                        ON CONFLICT (message_id, query_trace_id) DO NOTHING
                        """,
                        (message_id, query_trace_id),
                    )
                cursor.execute("UPDATE conversation SET updated_at = now() WHERE id = %s", (conversation_id,))
            connection.commit()
        return message_id

    def list_message_query_traces(self, message_id: int) -> list[str]:
        """Return query trace IDs associated with one assistant message."""

        self.initialize()
        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT query_trace_id
                    FROM message_query_trace
                    WHERE message_id = %s
                    ORDER BY id ASC
                    """,
                    (message_id,),
                )
                rows = cursor.fetchall()
        return [str(row[0]) for row in rows]

    def persist_agent_trace(self, trace_record: dict[str, Any]) -> None:
        """Persist one Agent Trace record and its ordered events to PostgreSQL."""

        self.initialize()
        from psycopg.types.json import Jsonb

        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO agent_trace (
                        agent_trace_id,
                        conversation_id,
                        message_id,
                        user_query,
                        intent_route,
                        allowed_tools,
                        query_trace_ids,
                        error,
                        started_at,
                        completed_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT (agent_trace_id) DO UPDATE SET
                        conversation_id = EXCLUDED.conversation_id,
                        message_id = EXCLUDED.message_id,
                        intent_route = EXCLUDED.intent_route,
                        allowed_tools = EXCLUDED.allowed_tools,
                        query_trace_ids = EXCLUDED.query_trace_ids,
                        error = EXCLUDED.error,
                        completed_at = EXCLUDED.completed_at
                    """,
                    (
                        trace_record.get("agent_trace_id"),
                        trace_record.get("conversation_id"),
                        trace_record.get("message_id"),
                        trace_record.get("user_query"),
                        Jsonb(trace_record.get("intent_route") or {}),
                        Jsonb(trace_record.get("allowed_tools") or []),
                        Jsonb(trace_record.get("query_trace_ids") or []),
                        trace_record.get("error"),
                        trace_record.get("started_at"),
                        trace_record.get("completed_at"),
                    ),
                )
                cursor.execute(
                    "DELETE FROM agent_trace_event WHERE agent_trace_id = %s",
                    (trace_record.get("agent_trace_id"),),
                )
                for event in trace_record.get("events") or []:
                    cursor.execute(
                        """
                        INSERT INTO agent_trace_event (
                            agent_trace_id,
                            event_type,
                            tool_name,
                            status,
                            duration_ms,
                            summary_payload,
                            error,
                            created_at
                        )
                        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                        """,
                        (
                            trace_record.get("agent_trace_id"),
                            event.get("event_type"),
                            event.get("tool_name"),
                            event.get("status"),
                            event.get("duration_ms"),
                            Jsonb(event.get("summary_payload") or {}),
                            event.get("error"),
                            event.get("created_at"),
                        ),
                    )
            connection.commit()

    def upsert_user_memory(
        self,
        user_id: int,
        *,
        memory_type: str,
        memory_value: str,
        evidence: str | None,
        confidence: float,
    ) -> None:
        self.initialize()
        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO user_memory (user_id, memory_type, memory_value, evidence, confidence)
                    VALUES (%s, %s, %s, %s, %s)
                    ON CONFLICT (user_id, memory_type, memory_value) DO UPDATE SET
                        evidence = COALESCE(EXCLUDED.evidence, user_memory.evidence),
                        confidence = GREATEST(user_memory.confidence, EXCLUDED.confidence),
                        updated_at = now()
                    """,
                    (user_id, memory_type, memory_value, evidence, confidence),
                )
            connection.commit()

    def list_conversations(self, *, user_id: int) -> list[AiModelConversationSummary]:
        self.initialize()
        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT id, title, created_at, updated_at
                    FROM conversation
                    WHERE user_id = %s
                    ORDER BY updated_at DESC, id DESC
                    """,
                    (user_id,),
                )
                rows = cursor.fetchall()
        return [
            AiModelConversationSummary(
                id=int(row[0]),
                title=row[1],
                created_at=row[2],
                updated_at=row[3],
            )
            for row in rows
        ]

    def list_messages(self, conversation_id: int, *, user_id: int) -> list[AiModelStoredMessage]:
        self.initialize()
        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT id, role, content, links, recommended_links, created_at
                    FROM message
                    WHERE conversation_id = %s AND user_id = %s
                    ORDER BY created_at ASC, id ASC
                    """,
                    (conversation_id, user_id),
                )
                rows = cursor.fetchall()
        return [
            AiModelStoredMessage(
                id=int(row[0]),
                role=row[1],
                content=row[2],
                links=list(row[3] or []),
                recommended_links=list(row[4] or []),
                created_at=row[5],
            )
            for row in rows
            if row[1] in {"user", "assistant"}
        ]

    def _connect(self):
        import psycopg

        return psycopg.connect(self.database_url)


def extract_user_memories_from_text(text: str, *, user_id: int) -> list[AiModelUserMemory]:
    memories: list[AiModelUserMemory] = []
    if any(keyword in text for keyword in ["高性价比", "便宜", "实惠", "预算有限"]):
        memories.append(
            AiModelUserMemory(
                memory_type="price_preference",
                memory_value="高性价比",
                evidence="用户表达了高性价比或预算敏感偏好。",
                confidence=0.7,
            )
        )

    for brand in _extract_brand_preferences(text):
        memories.append(
            AiModelUserMemory(
                memory_type="brand_preference",
                memory_value=brand,
                evidence=f"用户表达了对{brand}的品牌偏好。",
                confidence=0.8,
            )
        )

    return memories


def _extract_brand_preferences(text: str) -> list[str]:
    brands = ["小米", "华为", "苹果", "索尼", "戴森", "美的", "海尔", "耐克", "阿迪达斯"]
    if not any(keyword in text for keyword in ["喜欢", "偏好", "常买", "只看"]):
        return []
    return [brand for brand in brands if re.search(rf"(喜欢|偏好|常买|只看).{{0,8}}{brand}|{brand}.{{0,8}}(喜欢|偏好|常买|只看)", text)]


def _build_conversation_title(first_message: str) -> str:
    return first_message.strip().replace("\n", " ")[:40] or "新对话"


def _normalize_query_trace_ids(query_trace_ids: list[str] | None) -> list[str]:
    """Validate, trim, and de-duplicate query trace IDs while preserving order."""

    normalized: list[str] = []
    seen: set[str] = set()
    for value in query_trace_ids or []:
        if not isinstance(value, str) or not value.strip():
            raise ValueError("query_trace_ids must contain non-blank strings")
        trace_id = value.strip()
        if trace_id not in seen:
            normalized.append(trace_id)
            seen.add(trace_id)
    return normalized


@lru_cache(maxsize=1)
def get_aimodel_memory_store() -> AiModelMemoryStore:
    database_url = os.getenv("DATABASE_URL", "").strip()
    if database_url:
        return PostgresAiModelMemoryStore(database_url)
    return NoopAiModelMemoryStore()
