import os
import re
import threading
from dataclasses import dataclass
from functools import lru_cache
from typing import Literal, Protocol


POSTGRES_AIMODEL_MEMORY_SCHEMA_SQL = [
    """
    CREATE TABLE IF NOT EXISTS conversation (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id VARCHAR(64) NOT NULL,
        source VARCHAR(20) NOT NULL DEFAULT 'web',
        title VARCHAR(40),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_conversation_user_updated_at
    ON conversation(user_id, updated_at DESC, id DESC)
    """,
    """
    CREATE TABLE IF NOT EXISTS message (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        conversation_id INTEGER NOT NULL,
        user_id VARCHAR(64) NOT NULL,
        role VARCHAR(20) NOT NULL CHECK (role IN ('user', 'assistant')),
        content TEXT NOT NULL,
        links JSONB NOT NULL DEFAULT '[]'::jsonb,
        recommended_links JSONB NOT NULL DEFAULT '[]'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_message_conversation_created_at
    ON message(conversation_id, created_at DESC, id DESC)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_message_user_created_at
    ON message(user_id, created_at DESC, id DESC)
    """,
    """
    CREATE TABLE IF NOT EXISTS user_memory (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id VARCHAR(64) NOT NULL,
        memory_type VARCHAR(40) NOT NULL,
        memory_value VARCHAR(120) NOT NULL,
        evidence TEXT,
        confidence NUMERIC(4, 3) NOT NULL DEFAULT 0.500,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (user_id, memory_type, memory_value)
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_user_memory_user_type
    ON user_memory(user_id, memory_type, updated_at DESC)
    """,
]


@dataclass(frozen=True)
class AiModelMemoryMessage:
    role: Literal["user", "assistant"]
    content: str


@dataclass(frozen=True)
class AiModelUserMemory:
    memory_type: str
    memory_value: str
    evidence: str | None
    confidence: float


class AiModelMemoryStore(Protocol):
    def initialize(self) -> None: ...

    def ensure_conversation(self, conversation_id: int | None, *, user_id: str, first_message: str) -> int: ...

    def load_recent_messages(self, conversation_id: int, *, limit: int = 5) -> list[AiModelMemoryMessage]: ...

    def load_user_memories(self, user_id: str, *, limit: int = 10) -> list[AiModelUserMemory]: ...

    def append_user_message(self, conversation_id: int, *, user_id: str, content: str, links: list[str]) -> None: ...

    def append_assistant_message(
        self,
        conversation_id: int,
        *,
        user_id: str,
        content: str,
        recommended_links: list[dict[str, str]],
    ) -> None: ...

    def upsert_user_memory(
        self,
        user_id: str,
        *,
        memory_type: str,
        memory_value: str,
        evidence: str | None,
        confidence: float,
    ) -> None: ...


class NoopAiModelMemoryStore:
    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._next_conversation_id = 1
        self._messages: dict[int, list[AiModelMemoryMessage]] = {}
        self._memories: dict[str, dict[tuple[str, str], AiModelUserMemory]] = {}

    def initialize(self) -> None:
        return None

    def ensure_conversation(self, conversation_id: int | None, *, user_id: str, first_message: str) -> int:
        with self._lock:
            if conversation_id is not None:
                self._messages.setdefault(conversation_id, [])
                return conversation_id
            conversation_id = self._next_conversation_id
            self._next_conversation_id += 1
            self._messages.setdefault(conversation_id, [])
            return conversation_id

    def load_recent_messages(self, conversation_id: int, *, limit: int = 5) -> list[AiModelMemoryMessage]:
        with self._lock:
            return list(self._messages.get(conversation_id, [])[-limit:])

    def load_user_memories(self, user_id: str, *, limit: int = 10) -> list[AiModelUserMemory]:
        with self._lock:
            memories = list(self._memories.get(user_id, {}).values())
        return sorted(memories, key=lambda memory: memory.confidence, reverse=True)[:limit]

    def append_user_message(self, conversation_id: int, *, user_id: str, content: str, links: list[str]) -> None:
        with self._lock:
            self._messages.setdefault(conversation_id, []).append(AiModelMemoryMessage(role="user", content=content))

    def append_assistant_message(
        self,
        conversation_id: int,
        *,
        user_id: str,
        content: str,
        recommended_links: list[dict[str, str]],
    ) -> None:
        with self._lock:
            self._messages.setdefault(conversation_id, []).append(AiModelMemoryMessage(role="assistant", content=content))

    def upsert_user_memory(
        self,
        user_id: str,
        *,
        memory_type: str,
        memory_value: str,
        evidence: str | None,
        confidence: float,
    ) -> None:
        with self._lock:
            self._memories.setdefault(user_id, {})[(memory_type, memory_value)] = AiModelUserMemory(
                memory_type=memory_type,
                memory_value=memory_value,
                evidence=evidence,
                confidence=confidence,
            )


class PostgresAiModelMemoryStore:
    def __init__(self, database_url: str) -> None:
        self.database_url = database_url.replace("postgresql+psycopg://", "postgresql://")
        self._init_lock = threading.Lock()
        self._initialized = False

    def initialize(self) -> None:
        with self._init_lock:
            if self._initialized:
                return
            with self._connect() as connection:
                with connection.cursor() as cursor:
                    for statement in POSTGRES_AIMODEL_MEMORY_SCHEMA_SQL:
                        cursor.execute(statement)
                connection.commit()
            self._initialized = True

    def ensure_conversation(self, conversation_id: int | None, *, user_id: str, first_message: str) -> int:
        self.initialize()
        title = _build_conversation_title(first_message)
        with self._connect() as connection:
            with connection.cursor() as cursor:
                if conversation_id is None:
                    # 中文注释：首次对话由数据库生成数字会话 ID，前端后续用该 ID 继续窗口会话。
                    cursor.execute(
                        """
                        INSERT INTO conversation (user_id, source, title)
                        VALUES (%s, 'web', %s)
                        RETURNING id
                        """,
                        (user_id, title),
                    )
                    row = cursor.fetchone()
                    conversation_id = int(row[0])
                else:
                    # 中文注释：继续已有会话时只刷新更新时间，不依赖物理外键约束。
                    cursor.execute(
                        """
                        INSERT INTO conversation (id, user_id, source, title)
                        VALUES (%s, %s, 'web', %s)
                        ON CONFLICT (id) DO UPDATE SET
                            user_id = EXCLUDED.user_id,
                            updated_at = now()
                        """,
                        (conversation_id, user_id, title),
                    )
            connection.commit()
        return conversation_id

    def load_recent_messages(self, conversation_id: int, *, limit: int = 5) -> list[AiModelMemoryMessage]:
        self.initialize()
        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT role, content
                    FROM message
                    WHERE conversation_id = %s
                    ORDER BY created_at DESC, id DESC
                    LIMIT %s
                    """,
                    (conversation_id, limit),
                )
                rows = cursor.fetchall()
        return [
            AiModelMemoryMessage(role=row[0], content=row[1])
            for row in reversed(rows)
            if row[0] in {"user", "assistant"}
        ]

    def load_user_memories(self, user_id: str, *, limit: int = 10) -> list[AiModelUserMemory]:
        self.initialize()
        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT memory_type, memory_value, evidence, confidence
                    FROM user_memory
                    WHERE user_id = %s
                    ORDER BY confidence DESC, updated_at DESC, id DESC
                    LIMIT %s
                    """,
                    (user_id, limit),
                )
                rows = cursor.fetchall()
        return [
            AiModelUserMemory(
                memory_type=row[0],
                memory_value=row[1],
                evidence=row[2],
                confidence=float(row[3]),
            )
            for row in rows
        ]

    def append_user_message(self, conversation_id: int, *, user_id: str, content: str, links: list[str]) -> None:
        self.initialize()
        from psycopg.types.json import Jsonb

        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO message (conversation_id, user_id, role, content, links)
                    VALUES (%s, %s, 'user', %s, %s)
                    """,
                    (conversation_id, user_id, content, Jsonb(links)),
                )
                cursor.execute("UPDATE conversation SET updated_at = now() WHERE id = %s", (conversation_id,))
            connection.commit()

    def append_assistant_message(
        self,
        conversation_id: int,
        *,
        user_id: str,
        content: str,
        recommended_links: list[dict[str, str]],
    ) -> None:
        self.initialize()
        from psycopg.types.json import Jsonb

        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO message (conversation_id, user_id, role, content, recommended_links)
                    VALUES (%s, %s, 'assistant', %s, %s)
                    """,
                    (conversation_id, user_id, content, Jsonb(recommended_links)),
                )
                cursor.execute("UPDATE conversation SET updated_at = now() WHERE id = %s", (conversation_id,))
            connection.commit()

    def upsert_user_memory(
        self,
        user_id: str,
        *,
        memory_type: str,
        memory_value: str,
        evidence: str | None,
        confidence: float,
    ) -> None:
        self.initialize()
        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO user_memory (user_id, memory_type, memory_value, evidence, confidence)
                    VALUES (%s, %s, %s, %s, %s)
                    ON CONFLICT (user_id, memory_type, memory_value) DO UPDATE SET
                        evidence = COALESCE(EXCLUDED.evidence, user_memory.evidence),
                        confidence = GREATEST(user_memory.confidence, EXCLUDED.confidence),
                        updated_at = now()
                    """,
                    (user_id, memory_type, memory_value, evidence, confidence),
                )
            connection.commit()

    def _connect(self):
        import psycopg

        return psycopg.connect(self.database_url)


def extract_user_memories_from_text(text: str, *, user_id: str) -> list[AiModelUserMemory]:
    memories: list[AiModelUserMemory] = []
    if any(keyword in text for keyword in ["高性价比", "便宜", "实惠", "预算有限"]):
        memories.append(
            AiModelUserMemory(
                memory_type="price_preference",
                memory_value="高性价比",
                evidence="用户表达了高性价比或预算敏感偏好。",
                confidence=0.7,
            )
        )

    for brand in _extract_brand_preferences(text):
        memories.append(
            AiModelUserMemory(
                memory_type="brand_preference",
                memory_value=brand,
                evidence=f"用户表达了对{brand}的品牌偏好。",
                confidence=0.8,
            )
        )

    return memories


def _extract_brand_preferences(text: str) -> list[str]:
    brands = ["小米", "华为", "苹果", "索尼", "戴森", "美的", "海尔", "耐克", "阿迪达斯"]
    if not any(keyword in text for keyword in ["喜欢", "偏好", "常买", "只看"]):
        return []
    return [brand for brand in brands if re.search(rf"(喜欢|偏好|常买|只看).{{0,8}}{brand}|{brand}.{{0,8}}(喜欢|偏好|常买|只看)", text)]


def _build_conversation_title(first_message: str) -> str:
    return first_message.strip().replace("\n", " ")[:40] or "新对话"


@lru_cache(maxsize=1)
def get_aimodel_memory_store() -> AiModelMemoryStore:
    database_url = os.getenv("DATABASE_URL", "").strip()
    if database_url:
        return PostgresAiModelMemoryStore(database_url)
    return NoopAiModelMemoryStore()
