import os
import re
import threading
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from functools import lru_cache
from typing import Any, Callable, Literal, Protocol

from pydantic import ValidationError

from app.routers.AImodel.agent_trace import normalize_trace_event
from app.routers.AImodel.schemas import AiModelChatResponse


_LANGCHAIN_CHECKPOINTER_LOCK = threading.Lock()

_KNOWN_BRANDS = (
    "小米",
    "华为",
    "苹果",
    "索尼",
    "戴森",
    "美的",
    "海尔",
    "耐克",
    "阿迪达斯",
)
_REUSABLE_PREFERENCE_TERMS = ("长期", "一直", "平时", "常买", "喜欢", "偏好")
_EPHEMERAL_PREFERENCE_TERMS = ("这次", "本次", "当前", "今天", "临时")
_NEGATIVE_PREFERENCE_TERMS = (
    "不喜欢",
    "不偏好",
    "不想要",
    "不想买",
    "不考虑",
    "不要",
    "不买",
    "不选",
    "排斥",
    "讨厌",
    "取消偏好",
    "撤销偏好",
)
_HISTORICAL_PREFERENCE_TERMS = ("以前", "曾经", "过去")

POSTGRES_AIMODEL_MEMORY_SCHEMA_SQL = [
    """
    CREATE TABLE IF NOT EXISTS conversation (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        source VARCHAR(20) NOT NULL DEFAULT 'web',
        title VARCHAR(40),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_conversation_user_updated_at
    ON conversation(user_id, updated_at DESC, id DESC)
    """,
    """
    CREATE TABLE IF NOT EXISTS message (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        conversation_id INTEGER NOT NULL,
        user_id INTEGER NOT NULL,
        role VARCHAR(20) NOT NULL CHECK (role IN ('user', 'assistant')),
        content TEXT NOT NULL,
        links JSONB NOT NULL DEFAULT '[]'::jsonb,
        recommended_links JSONB NOT NULL DEFAULT '[]'::jsonb,
        structured_response JSONB,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    ALTER TABLE message
    ADD COLUMN IF NOT EXISTS structured_response JSONB
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_message_conversation_created_at
    ON message(conversation_id, created_at DESC, id DESC)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_message_user_created_at
    ON message(user_id, created_at DESC, id DESC)
    """,
    """
    CREATE TABLE IF NOT EXISTS message_query_trace (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        message_id INTEGER NOT NULL,
        query_trace_id TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (message_id, query_trace_id)
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_message_query_trace_message_id
    ON message_query_trace(message_id, id ASC)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_message_query_trace_trace_id
    ON message_query_trace(query_trace_id)
    """,
    """
    CREATE TABLE IF NOT EXISTS agent_trace (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        agent_trace_id TEXT NOT NULL UNIQUE,
        trace_schema_version VARCHAR(20) NOT NULL DEFAULT 'v1',
        status VARCHAR(20) NOT NULL DEFAULT 'success',
        conversation_id INTEGER,
        message_id INTEGER,
        user_query TEXT NOT NULL,
        intent_route JSONB NOT NULL DEFAULT '{}'::jsonb,
        allowed_tools JSONB NOT NULL DEFAULT '[]'::jsonb,
        query_trace_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
        error TEXT,
        started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        completed_at TIMESTAMPTZ
    )
    """,
    """
    ALTER TABLE agent_trace
    ADD COLUMN IF NOT EXISTS trace_schema_version VARCHAR(20) NOT NULL DEFAULT 'v1'
    """,
    """
    ALTER TABLE agent_trace
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'success'
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agent_trace_conversation
    ON agent_trace(conversation_id, started_at DESC, id DESC)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agent_trace_message
    ON agent_trace(message_id, started_at DESC, id DESC)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agent_trace_query_trace_ids
    ON agent_trace USING GIN(query_trace_ids)
    """,
    """
    CREATE TABLE IF NOT EXISTS agent_trace_event (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        agent_trace_id TEXT NOT NULL,
        event_id TEXT,
        event_type VARCHAR(40) NOT NULL,
        stage VARCHAR(40),
        tool_name VARCHAR(120),
        status VARCHAR(30) NOT NULL,
        duration_ms NUMERIC(12, 3),
        summary_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
        related_ids JSONB NOT NULL DEFAULT '{}'::jsonb,
        error TEXT,
        started_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    ALTER TABLE agent_trace_event
    ADD COLUMN IF NOT EXISTS event_id TEXT
    """,
    """
    ALTER TABLE agent_trace_event
    ADD COLUMN IF NOT EXISTS stage VARCHAR(40)
    """,
    """
    ALTER TABLE agent_trace_event
    ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ
    """,
    """
    ALTER TABLE agent_trace_event
    ADD COLUMN IF NOT EXISTS related_ids JSONB NOT NULL DEFAULT '{}'::jsonb
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agent_trace_event_trace_created
    ON agent_trace_event(agent_trace_id, created_at ASC, id ASC)
    """,
    """
    CREATE TABLE IF NOT EXISTS user_memory (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        memory_type VARCHAR(40) NOT NULL,
        memory_value VARCHAR(512) NOT NULL,
        evidence TEXT,
        confidence NUMERIC(4, 3) NOT NULL DEFAULT 0.500,
        expires_at TIMESTAMPTZ,
        source_goal_id TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (user_id, memory_type, memory_value)
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_user_memory_user_type
    ON user_memory(user_id, memory_type, updated_at DESC)
    """,
    """
    ALTER TABLE user_memory
    ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ
    """,
    """
    ALTER TABLE user_memory
    ADD COLUMN IF NOT EXISTS source_goal_id TEXT
    """,
    """
    ALTER TABLE user_memory
    ALTER COLUMN memory_value TYPE VARCHAR(512)
    """,
    """
    ALTER TABLE conversation
    ALTER COLUMN user_id TYPE INTEGER USING user_id::integer
    """,
    """
    ALTER TABLE message
    ALTER COLUMN user_id TYPE INTEGER USING user_id::integer
    """,
    """
    ALTER TABLE user_memory
    ALTER COLUMN user_id TYPE INTEGER USING user_id::integer
    """,
    """
    CREATE TABLE IF NOT EXISTS shopping_goal_state (
        goal_id TEXT PRIMARY KEY,
        conversation_id INTEGER NOT NULL UNIQUE,
        user_id INTEGER NOT NULL,
        schema_version VARCHAR(20) NOT NULL,
        revision INTEGER NOT NULL CHECK (revision >= 0),
        payload JSONB NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_shopping_goal_state_user_updated
    ON shopping_goal_state(user_id, updated_at DESC)
    """,
    """
    CREATE TABLE IF NOT EXISTS shopping_goal_event (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id TEXT NOT NULL UNIQUE,
        goal_id TEXT NOT NULL,
        conversation_id INTEGER NOT NULL,
        user_id INTEGER NOT NULL,
        revision INTEGER NOT NULL CHECK (revision >= 0),
        payload JSONB NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_shopping_goal_event_goal_revision
    ON shopping_goal_event(goal_id, revision ASC, id ASC)
    """,
]


@dataclass(frozen=True)
class AiModelMemoryMessage:
    role: Literal["user", "assistant"]
    content: str


@dataclass(frozen=True)
class AiModelUserMemory:
    memory_type: str
    memory_value: str
    evidence: str | None
    confidence: float
    expires_at: datetime | None = None
    source_goal_id: str | None = None


@dataclass(frozen=True)
class AiModelConversationSummary:
    id: int
    title: str | None
    created_at: datetime | None = None
    updated_at: datetime | None = None


@dataclass(frozen=True)
class AiModelStoredMessage:
    id: int
    role: Literal["user", "assistant"]
    content: str
    links: list[str]
    recommended_links: list[dict[str, Any]]
    structured_response: dict[str, Any] | None = None
    created_at: datetime | None = None


class AiModelMemoryStore(Protocol):
    def initialize(self) -> None: ...

    def ensure_conversation(
        self, conversation_id: int | None, *, user_id: int, first_message: str
    ) -> int: ...

    def load_recent_messages(
        self, conversation_id: int, *, limit: int = 5
    ) -> list[AiModelMemoryMessage]: ...

    def load_user_memories(
        self, user_id: int, *, limit: int = 10
    ) -> list[AiModelUserMemory]: ...

    def append_user_message(
        self, conversation_id: int, *, user_id: int, content: str, links: list[str]
    ) -> None: ...

    def append_assistant_message(
        self,
        conversation_id: int,
        *,
        user_id: int,
        content: str,
        recommended_links: list[dict[str, str]],
        query_trace_ids: list[str] | None = None,
        structured_response: dict[str, Any] | None = None,
    ) -> int: ...

    def list_message_query_traces(self, message_id: int) -> list[str]: ...

    def persist_agent_trace(self, trace_record: dict[str, Any]) -> None: ...

    def upsert_user_memory(
        self,
        user_id: int,
        *,
        memory_type: str,
        memory_value: str,
        evidence: str | None,
        confidence: float,
        expires_at: datetime | None = None,
        source_goal_id: str | None = None,
    ) -> None: ...

    def list_conversations(
        self, *, user_id: int
    ) -> list[AiModelConversationSummary]: ...

    def list_messages(
        self, conversation_id: int, *, user_id: int
    ) -> list[AiModelStoredMessage]: ...


class NoopAiModelMemoryStore:
    def __init__(
        self,
        *,
        clock: Callable[[], datetime] = lambda: datetime.now(UTC),
    ) -> None:
        self._clock = clock
        self._lock = threading.Lock()
        self._next_conversation_id = 1
        self._next_message_id = 1
        self._next_sort_order = 1
        self._conversations: dict[int, tuple[int, str, int]] = {}
        self._messages: dict[int, list[AiModelStoredMessage]] = {}
        self._message_query_traces: dict[int, list[str]] = {}
        self._memories: dict[int, dict[tuple[str, str], AiModelUserMemory]] = {}

    def initialize(self) -> None:
        return None

    def ensure_conversation(
        self, conversation_id: int | None, *, user_id: int, first_message: str
    ) -> int:
        with self._lock:
            if conversation_id is not None:
                self._conversations.setdefault(
                    conversation_id,
                    (
                        user_id,
                        _build_conversation_title(first_message),
                        self._next_sort_order,
                    ),
                )
                self._next_sort_order += 1
                self._messages.setdefault(conversation_id, [])
                return conversation_id
            conversation_id = self._next_conversation_id
            self._next_conversation_id += 1
            self._conversations[conversation_id] = (
                user_id,
                _build_conversation_title(first_message),
                self._next_sort_order,
            )
            self._next_sort_order += 1
            self._messages.setdefault(conversation_id, [])
            return conversation_id

    def load_recent_messages(
        self, conversation_id: int, *, limit: int = 5
    ) -> list[AiModelMemoryMessage]:
        with self._lock:
            return [
                AiModelMemoryMessage(role=message.role, content=message.content)
                for message in self._messages.get(conversation_id, [])[-limit:]
            ]

    def load_user_memories(
        self, user_id: int, *, limit: int = 10
    ) -> list[AiModelUserMemory]:
        with self._lock:
            now = self._clock()
            memories = [
                memory
                for memory in self._memories.get(user_id, {}).values()
                if memory.expires_at is None or memory.expires_at > now
            ]
        return sorted(memories, key=lambda memory: memory.confidence, reverse=True)[
            :limit
        ]

    def append_user_message(
        self, conversation_id: int, *, user_id: int, content: str, links: list[str]
    ) -> None:
        with self._lock:
            # 中文注释：Noop store 也保留完整消息结构，保证前端会话历史测试不依赖真实数据库。
            self._messages.setdefault(conversation_id, []).append(
                AiModelStoredMessage(
                    id=self._next_message_id,
                    role="user",
                    content=content,
                    links=links,
                    recommended_links=[],
                    structured_response=None,
                )
            )
            self._next_message_id += 1

    def append_assistant_message(
        self,
        conversation_id: int,
        *,
        user_id: int,
        content: str,
        recommended_links: list[dict[str, str]],
        query_trace_ids: list[str] | None = None,
        structured_response: dict[str, Any] | None = None,
    ) -> int:
        normalized_response = _structured_response_or_fallback(
            conversation_id=conversation_id,
            content=content,
            recommended_links=recommended_links,
            structured_response=structured_response,
        )
        with self._lock:
            message_id = self._next_message_id
            self._messages.setdefault(conversation_id, []).append(
                AiModelStoredMessage(
                    id=message_id,
                    role="assistant",
                    content=content,
                    links=[],
                    recommended_links=recommended_links,
                    structured_response=normalized_response,
                )
            )
            self._next_message_id += 1
            self._message_query_traces[message_id] = _normalize_query_trace_ids(
                query_trace_ids
            )
            return message_id

    def list_message_query_traces(self, message_id: int) -> list[str]:
        """Return query traces consumed by one stored assistant message."""

        with self._lock:
            return list(self._message_query_traces.get(message_id, []))

    def persist_agent_trace(self, trace_record: dict[str, Any]) -> None:
        """Accept Agent Trace records in tests without external storage."""

        return None

    def upsert_user_memory(
        self,
        user_id: int,
        *,
        memory_type: str,
        memory_value: str,
        evidence: str | None,
        confidence: float,
        expires_at: datetime | None = None,
        source_goal_id: str | None = None,
    ) -> None:
        with self._lock:
            user_memories = self._memories.setdefault(user_id, {})
            key = (memory_type, memory_value)
            current = user_memories.get(key)
            if current is not None:
                confidence = max(current.confidence, confidence)
                if current.expires_at is not None and (
                    expires_at is None or current.expires_at > expires_at
                ):
                    expires_at = current.expires_at
                evidence = evidence or current.evidence
                source_goal_id = source_goal_id or current.source_goal_id
            user_memories[key] = AiModelUserMemory(
                memory_type=memory_type,
                memory_value=memory_value,
                evidence=evidence,
                confidence=confidence,
                expires_at=expires_at,
                source_goal_id=source_goal_id,
            )

    def list_conversations(self, *, user_id: int) -> list[AiModelConversationSummary]:
        with self._lock:
            conversations = [
                AiModelConversationSummary(id=conversation_id, title=title)
                for conversation_id, (
                    stored_user_id,
                    title,
                    _sort_order,
                ) in self._conversations.items()
                if stored_user_id == user_id
            ]
            sort_orders = {
                conversation_id: sort_order
                for conversation_id, (
                    stored_user_id,
                    _title,
                    sort_order,
                ) in self._conversations.items()
                if stored_user_id == user_id
            }
        return sorted(
            conversations,
            key=lambda conversation: sort_orders[conversation.id],
            reverse=True,
        )

    def list_messages(
        self, conversation_id: int, *, user_id: int
    ) -> list[AiModelStoredMessage]:
        with self._lock:
            conversation = self._conversations.get(conversation_id)
            if conversation is None or conversation[0] != user_id:
                return []
            return list(self._messages.get(conversation_id, []))


class PostgresAiModelMemoryStore:
    def __init__(self, database_url: str) -> None:
        self.database_url = database_url.replace(
            "postgresql+psycopg://", "postgresql://"
        )
        self._init_lock = threading.Lock()
        self._initialized = False

    def initialize(self) -> None:
        with self._init_lock:
            if self._initialized:
                return
            with self._connect() as connection:
                with connection.cursor() as cursor:
                    for statement in POSTGRES_AIMODEL_MEMORY_SCHEMA_SQL:
                        cursor.execute(statement)
                connection.commit()
            self._initialized = True

    def ensure_conversation(
        self, conversation_id: int | None, *, user_id: int, first_message: str
    ) -> int:
        self.initialize()
        title = _build_conversation_title(first_message)
        with self._connect() as connection:
            with connection.cursor() as cursor:
                if conversation_id is None:
                    # 中文注释：首次对话由数据库生成数字会话 ID，前端后续用该 ID 继续窗口会话。
                    cursor.execute(
                        """
                        INSERT INTO conversation (user_id, source, title)
                        VALUES (%s, 'web', %s)
                        RETURNING id
                        """,
                        (user_id, title),
                    )
                    row = cursor.fetchone()
                    conversation_id = int(row[0])
                else:
                    # 中文注释：继续已有会话时只刷新更新时间，不依赖物理外键约束。
                    cursor.execute(
                        """
                        INSERT INTO conversation (id, user_id, source, title)
                        VALUES (%s, %s, 'web', %s)
                        ON CONFLICT (id) DO UPDATE SET
                            user_id = EXCLUDED.user_id,
                            updated_at = now()
                        """,
                        (conversation_id, user_id, title),
                    )
            connection.commit()
        return conversation_id

    def load_recent_messages(
        self, conversation_id: int, *, limit: int = 5
    ) -> list[AiModelMemoryMessage]:
        self.initialize()
        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT role, content
                    FROM message
                    WHERE conversation_id = %s
                    ORDER BY created_at DESC, id DESC
                    LIMIT %s
                    """,
                    (conversation_id, limit),
                )
                rows = cursor.fetchall()
        return [
            AiModelMemoryMessage(role=row[0], content=row[1])
            for row in reversed(rows)
            if row[0] in {"user", "assistant"}
        ]

    def load_user_memories(
        self, user_id: int, *, limit: int = 10
    ) -> list[AiModelUserMemory]:
        self.initialize()
        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT memory_type, memory_value, evidence, confidence,
                           expires_at, source_goal_id
                    FROM user_memory
                    WHERE user_id = %s
                      AND (expires_at IS NULL OR expires_at > now())
                    ORDER BY confidence DESC, updated_at DESC, id DESC
                    LIMIT %s
                    """,
                    (user_id, limit),
                )
                rows = cursor.fetchall()
        return [
            AiModelUserMemory(
                memory_type=row[0],
                memory_value=row[1],
                evidence=row[2],
                confidence=float(row[3]),
                expires_at=row[4],
                source_goal_id=row[5],
            )
            for row in rows
        ]

    def append_user_message(
        self, conversation_id: int, *, user_id: int, content: str, links: list[str]
    ) -> None:
        self.initialize()
        from psycopg.types.json import Jsonb

        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO message (conversation_id, user_id, role, content, links)
                    VALUES (%s, %s, 'user', %s, %s)
                    """,
                    (conversation_id, user_id, content, Jsonb(links)),
                )
                cursor.execute(
                    "UPDATE conversation SET updated_at = now() WHERE id = %s",
                    (conversation_id,),
                )
            connection.commit()

    def append_assistant_message(
        self,
        conversation_id: int,
        *,
        user_id: int,
        content: str,
        recommended_links: list[dict[str, str]],
        query_trace_ids: list[str] | None = None,
        structured_response: dict[str, Any] | None = None,
    ) -> int:
        self.initialize()
        from psycopg.types.json import Jsonb

        normalized_response = _structured_response_or_fallback(
            conversation_id=conversation_id,
            content=content,
            recommended_links=recommended_links,
            structured_response=structured_response,
        )
        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO message (
                        conversation_id,
                        user_id,
                        role,
                        content,
                        recommended_links,
                        structured_response
                    )
                    VALUES (%s, %s, 'assistant', %s, %s, %s)
                    RETURNING id
                    """,
                    (
                        conversation_id,
                        user_id,
                        content,
                        Jsonb(recommended_links),
                        Jsonb(normalized_response),
                    ),
                )
                message_id = int(cursor.fetchone()[0])
                for query_trace_id in _normalize_query_trace_ids(query_trace_ids):
                    cursor.execute(
                        """
                        INSERT INTO message_query_trace (message_id, query_trace_id)
                        VALUES (%s, %s)
                        ON CONFLICT (message_id, query_trace_id) DO NOTHING
                        """,
                        (message_id, query_trace_id),
                    )
                cursor.execute(
                    "UPDATE conversation SET updated_at = now() WHERE id = %s",
                    (conversation_id,),
                )
            connection.commit()
        return message_id

    def list_message_query_traces(self, message_id: int) -> list[str]:
        """Return query trace IDs associated with one assistant message."""

        self.initialize()
        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT query_trace_id
                    FROM message_query_trace
                    WHERE message_id = %s
                    ORDER BY id ASC
                    """,
                    (message_id,),
                )
                rows = cursor.fetchall()
        return [str(row[0]) for row in rows]

    def persist_agent_trace(self, trace_record: dict[str, Any]) -> None:
        """Persist one Agent Trace record and its ordered events to PostgreSQL."""

        self.initialize()
        from psycopg.types.json import Jsonb

        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO agent_trace (
                        agent_trace_id,
                        trace_schema_version,
                        status,
                        conversation_id,
                        message_id,
                        user_query,
                        intent_route,
                        allowed_tools,
                        query_trace_ids,
                        error,
                        started_at,
                        completed_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT (agent_trace_id) DO UPDATE SET
                        trace_schema_version = EXCLUDED.trace_schema_version,
                        status = EXCLUDED.status,
                        conversation_id = EXCLUDED.conversation_id,
                        message_id = EXCLUDED.message_id,
                        intent_route = EXCLUDED.intent_route,
                        allowed_tools = EXCLUDED.allowed_tools,
                        query_trace_ids = EXCLUDED.query_trace_ids,
                        error = EXCLUDED.error,
                        completed_at = EXCLUDED.completed_at
                    """,
                    (
                        trace_record.get("agent_trace_id"),
                        trace_record.get("trace_schema_version", "v1"),
                        trace_record.get("status", "success"),
                        trace_record.get("conversation_id"),
                        trace_record.get("message_id"),
                        trace_record.get("user_query"),
                        Jsonb(trace_record.get("intent_route") or {}),
                        Jsonb(trace_record.get("allowed_tools") or []),
                        Jsonb(trace_record.get("query_trace_ids") or []),
                        trace_record.get("error"),
                        trace_record.get("started_at"),
                        trace_record.get("completed_at"),
                    ),
                )
                cursor.execute(
                    "DELETE FROM agent_trace_event WHERE agent_trace_id = %s",
                    (trace_record.get("agent_trace_id"),),
                )
                for sequence, raw_event in enumerate(
                    trace_record.get("events") or [], start=1
                ):
                    event = normalize_trace_event(
                        raw_event,
                        trace_id=str(trace_record.get("agent_trace_id") or ""),
                        sequence=sequence,
                    )
                    cursor.execute(
                        """
                        INSERT INTO agent_trace_event (
                            agent_trace_id,
                            event_id,
                            event_type,
                            stage,
                            tool_name,
                            status,
                            duration_ms,
                            summary_payload,
                            related_ids,
                            error,
                            started_at,
                            created_at
                        )
                        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                        """,
                        (
                            trace_record.get("agent_trace_id"),
                            event.get("event_id"),
                            event.get("event_type"),
                            event.get("stage"),
                            event.get("tool_name"),
                            event.get("status"),
                            event.get("duration_ms"),
                            Jsonb(event.get("summary_payload") or {}),
                            Jsonb(event.get("related_ids") or {}),
                            event.get("error"),
                            event.get("started_at"),
                            event.get("created_at"),
                        ),
                    )
            connection.commit()

    def upsert_user_memory(
        self,
        user_id: int,
        *,
        memory_type: str,
        memory_value: str,
        evidence: str | None,
        confidence: float,
        expires_at: datetime | None = None,
        source_goal_id: str | None = None,
    ) -> None:
        self.initialize()
        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO user_memory (
                        user_id, memory_type, memory_value, evidence, confidence,
                        expires_at, source_goal_id
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT (user_id, memory_type, memory_value) DO UPDATE SET
                        evidence = COALESCE(EXCLUDED.evidence, user_memory.evidence),
                        confidence = GREATEST(user_memory.confidence, EXCLUDED.confidence),
                        expires_at = GREATEST(
                            user_memory.expires_at,
                            EXCLUDED.expires_at
                        ),
                        source_goal_id = COALESCE(
                            EXCLUDED.source_goal_id,
                            user_memory.source_goal_id
                        ),
                        updated_at = now()
                    """,
                    (
                        user_id,
                        memory_type,
                        memory_value,
                        evidence,
                        confidence,
                        expires_at,
                        source_goal_id,
                    ),
                )
            connection.commit()

    def list_conversations(self, *, user_id: int) -> list[AiModelConversationSummary]:
        self.initialize()
        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT id, title, created_at, updated_at
                    FROM conversation
                    WHERE user_id = %s
                    ORDER BY updated_at DESC, id DESC
                    """,
                    (user_id,),
                )
                rows = cursor.fetchall()
        return [
            AiModelConversationSummary(
                id=int(row[0]),
                title=row[1],
                created_at=row[2],
                updated_at=row[3],
            )
            for row in rows
        ]

    def list_messages(
        self, conversation_id: int, *, user_id: int
    ) -> list[AiModelStoredMessage]:
        self.initialize()
        with self._connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT
                        id,
                        role,
                        content,
                        links,
                        recommended_links,
                        structured_response,
                        created_at
                    FROM message
                    WHERE conversation_id = %s AND user_id = %s
                    ORDER BY created_at ASC, id ASC
                    """,
                    (conversation_id, user_id),
                )
                rows = cursor.fetchall()
        return [
            AiModelStoredMessage(
                id=int(row[0]),
                role=row[1],
                content=row[2],
                links=list(row[3] or []),
                recommended_links=list(row[4] or []),
                structured_response=(
                    _structured_response_or_fallback(
                        conversation_id=conversation_id,
                        content=row[2],
                        recommended_links=list(row[4] or []),
                        structured_response=row[5],
                    )
                    if row[1] == "assistant"
                    else None
                ),
                created_at=row[6],
            )
            for row in rows
            if row[1] in {"user", "assistant"}
        ]

    def _connect(self):
        import psycopg

        return psycopg.connect(self.database_url)


def _structured_response_or_fallback(
    *,
    conversation_id: int,
    content: str,
    recommended_links: list[dict[str, Any]],
    structured_response: dict[str, Any] | None,
) -> dict[str, Any]:
    if structured_response:
        try:
            return AiModelChatResponse.model_validate(structured_response).model_dump(
                mode="json"
            )
        except (TypeError, ValidationError):
            pass

    answer = content.strip() or "历史消息内容为空。"
    try:
        response = AiModelChatResponse.from_legacy(
            answer=answer,
            recommended_links=recommended_links,
            conversation_id=conversation_id,
        )
    except (TypeError, ValidationError):
        response = AiModelChatResponse.from_legacy(
            answer=answer,
            recommended_links=[],
            conversation_id=conversation_id,
        )
    return response.model_dump(mode="json")


def extract_user_memories_from_text(
    text: str,
    *,
    user_id: int,
    now: datetime | None = None,
) -> list[AiModelUserMemory]:
    if user_id <= 0:
        raise ValueError("user_id must be positive")
    reference_time = now or datetime.now(UTC)
    memories: list[AiModelUserMemory] = []
    for brand in _extract_brand_preferences(text):
        memories.append(
            AiModelUserMemory(
                memory_type="brand_preference",
                memory_value=brand,
                evidence=text.strip()[:512],
                confidence=0.8,
                expires_at=reference_time + timedelta(days=180),
            )
        )

    return memories


def _extract_brand_preferences(text: str) -> list[str]:
    return [
        brand
        for brand in _KNOWN_BRANDS
        if is_explicit_reusable_brand_preference(text, brand)
    ]


def is_explicit_reusable_brand_preference(text: str, brand: str) -> bool:
    """Return true only for current, positive, cross-session brand preferences."""

    normalized_text = text.strip()
    normalized_brand = brand.strip()
    if not normalized_text or not normalized_brand:
        return False

    clauses = [
        clause.strip()
        for clause in re.split(
            r"[，,。；;！？!?\n]|(?:但是|但|不过|而是|却)", normalized_text
        )
        if clause.strip()
    ]
    for index, clause in enumerate(clauses):
        if normalized_brand not in clause:
            continue
        if any(term in clause for term in _EPHEMERAL_PREFERENCE_TERMS):
            continue
        if any(term in clause for term in _NEGATIVE_PREFERENCE_TERMS):
            continue
        if (
            any(term in clause for term in _HISTORICAL_PREFERENCE_TERMS)
            and "一直" not in clause
        ):
            continue
        if index + 1 < len(clauses):
            following = clauses[index + 1]
            has_explicit_brand = any(brand in following for brand in _KNOWN_BRANDS)
            if not has_explicit_brand and any(
                term in following for term in _NEGATIVE_PREFERENCE_TERMS
            ):
                continue
        if re.search(
            rf"(?:{'|'.join(_REUSABLE_PREFERENCE_TERMS)}).{{0,8}}{re.escape(normalized_brand)}|"
            rf"{re.escape(normalized_brand)}.{{0,8}}(?:{'|'.join(_REUSABLE_PREFERENCE_TERMS)})",
            clause,
        ):
            return True
    return False


class FallbackLangChainCheckpointer:
    """Minimal checkpointer shape used when LangGraph is unavailable in tests."""

    def get_tuple(self, *_args: Any, **_kwargs: Any) -> None:
        return None

    def put(self, *_args: Any, **_kwargs: Any) -> None:
        return None


def _build_conversation_title(first_message: str) -> str:
    return first_message.strip().replace("\n", " ")[:40] or "新对话"


def _normalize_query_trace_ids(query_trace_ids: list[str] | None) -> list[str]:
    """Validate, trim, and de-duplicate query trace IDs while preserving order."""

    normalized: list[str] = []
    seen: set[str] = set()
    for value in query_trace_ids or []:
        if not isinstance(value, str) or not value.strip():
            raise ValueError("query_trace_ids must contain non-blank strings")
        trace_id = value.strip()
        if trace_id not in seen:
            normalized.append(trace_id)
            seen.add(trace_id)
    return normalized


@lru_cache(maxsize=1)
def _create_langchain_checkpointer() -> Any:
    """Create the LangGraph checkpointer for the current process."""

    database_url = os.getenv("DATABASE_URL", "").strip()
    if database_url:
        import psycopg
        from langgraph.checkpoint.postgres import PostgresSaver
        from psycopg.rows import dict_row

        connection = psycopg.Connection.connect(
            database_url.replace("postgresql+psycopg://", "postgresql://"),
            autocommit=True,
            prepare_threshold=0,
            row_factory=dict_row,
        )
        saver = PostgresSaver(connection)
        saver.setup()
        return saver

    try:
        from langgraph.checkpoint.memory import MemorySaver
    except Exception:
        return FallbackLangChainCheckpointer()
    return MemorySaver()


def get_langchain_checkpointer() -> Any:
    """Return the process-level LangGraph checkpointer used by AImodel agents."""

    with _LANGCHAIN_CHECKPOINTER_LOCK:
        return _create_langchain_checkpointer()


get_langchain_checkpointer.cache_clear = _create_langchain_checkpointer.cache_clear  # type: ignore[attr-defined]


def build_langchain_config(conversation_id: int) -> dict[str, dict[str, str]]:
    """Build the LangChain config that binds one conversation to one thread."""

    if conversation_id <= 0:
        raise ValueError("conversation_id must be a positive integer")
    return {"configurable": {"thread_id": str(conversation_id)}}


@lru_cache(maxsize=1)
def get_aimodel_memory_store() -> AiModelMemoryStore:
    database_url = os.getenv("DATABASE_URL", "").strip()
    if database_url:
        return PostgresAiModelMemoryStore(database_url)
    return NoopAiModelMemoryStore()
